name: 🐳 CI/CD

# Cancel in-progress jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ⚡️ Init
        uses: ./.github/init

  codeQL:
    needs: init
    strategy:
      matrix:
        tasks: ["lint", "prettier", "build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚡️ Restore
        uses: ./.github/restore

      - uses: actions/cache@v4
        name: Setup turbo cache
        with:
          path: |
            **/.turbo
            .turbo
          key: ${{ runner.os }}-${{matrix.tasks}}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.tasks}}-turbo-

      - name: ✨ Run Task ${{ matrix.tasks }}
        run: pnpm run ${{ matrix.tasks }}

  deploy:
    permissions:
      contents: read
      deployments: write
    needs:  ['codeQL']
    if: ${{ contains(fromJSON('["refs/heads/main"]'), github.ref) }}
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
