name: 🌍 Deploy @urbanradar/frontend

on:
  workflow_call:
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚡️ Init
        uses: ./.github/init

      - name: 🔨 Build the frontend
        run: pnpm run build --filter=@alareis/frontend 
      
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/alareis-frontend"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=alareis-frontend
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}