name: 🌍 Deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit

  frontend:
    uses: ./.github/workflows/deploy-frontend.yaml
    secrets: inherit

